compositionIdentifier: example.cloud
provider:
  baseURL: https://raw.githubusercontent.com/crossplane-contrib/%s/%s/package/crds/%s
  name: provider-aws
  version: "v0.38.0"
labels:
  fromCRD:
  - example-company/psp-element
tags:
  fromLabels:
  - example-company/psp-element