---
apiVersion: s3.aws.example.cloud/v1alpha1
kind: Bucket
metadata:
  name: example-bucket
  namespace: assert-bucket
  labels:
    controlling.example.cloud/cost-reference: "123456789"
    controlling.example.cloud/owner: example
    controlling.example.cloud/product: example
    tags.example.cloud/account: "123456789101"
    tags.example.cloud/zone: "dev"
    tags.example.cloud/environment: "dev"
    tags.example.cloud/protection-requirement: "dev"
    tags.example.cloud/repourl: "x-generate"
  annotations:
    crossplane.io/external-name: example-bucket-test
    uptest.upbound.io/conditions: "Ready=False"
    uptest.upbound.io/post-assert-hook: "../../test/tests/package/s3-bucket/post-assert.sh ${KUBECTL} ${KUTTL}"
spec:
  forProvider:
    acl: private
    locationConstraint: eu-central-1
    paymentConfiguration:
      payer: BucketOwner
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
            sseAlgorithm: AES256
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: 123456789101-example
